/**
 * Seed the Supabase `plants` table with the built-in plant list.
 * Run with: node scripts/seed-plants.mjs
 */

import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'

// Load .env.local manually (Vite env files aren't picked up by Node)
const __dirname = dirname(fileURLToPath(import.meta.url))
const envPath = resolve(__dirname, '../.env.local')
const env = Object.fromEntries(
  readFileSync(envPath, 'utf8')
    .split('\n')
    .filter(l => l.includes('='))
    .map(l => l.split('=').map(s => s.trim()))
)

const supabase = createClient(
  env.VITE_SUPABASE_URL,
  env.VITE_SUPABASE_ANON_KEY
)

// Inline plant data — mirrors src/data/plants.js
const plants = [
  { id: 'tomato',      name: 'Tomato',      icon: 'tomato.png',       plants_per_square: 1,  companions: ['basil','carrot','marigold','nasturtium','chamomile'], competitors: ['potato','corn'], incompatible: ['fennel'], notes: 'Needs full sun. Stake or cage when planting.', timing: { cold: { indoor_start: 'Feb–Mar', transplant: 'Jun–Jul', direct_sow: null, harvest: 'Aug–Oct' }, temperate: { indoor_start: 'Feb–Apr', transplant: 'May–Jun', direct_sow: null, harvest: 'Jul–Sep' }, warm: { indoor_start: 'Jan–Mar', transplant: 'Mar–May', direct_sow: null, harvest: 'Jun–Sep' }, hot: { indoor_start: null, transplant: 'Feb–Apr', direct_sow: 'Jan–Mar', harvest: 'Apr–Jul' } } },
  { id: 'basil',       name: 'Basil',       icon: 'basil.png',        plants_per_square: 4,  companions: ['tomato','pepper','marigold'], competitors: [], incompatible: ['fennel'], notes: 'Repels aphids and whiteflies. Pinch flowers to extend harvest.', timing: { cold: { indoor_start: 'Apr–May', transplant: 'Jun', direct_sow: null, harvest: 'Jul–Sep' }, temperate: { indoor_start: 'Mar–Apr', transplant: 'May–Jun', direct_sow: 'May–Jun', harvest: 'Jun–Sep' }, warm: { indoor_start: 'Feb–Mar', transplant: 'Apr–May', direct_sow: 'Apr–May', harvest: 'May–Sep' }, hot: { indoor_start: null, transplant: 'Mar–Apr', direct_sow: 'Mar–Apr', harvest: 'Apr–Oct' } } },
  { id: 'carrot',      name: 'Carrot',      icon: 'carrot.png',       plants_per_square: 16, companions: ['tomato','lettuce','onion','pea','radish','chamomile'], competitors: [], incompatible: ['dill'], notes: 'Needs loose, deep soil. Thin to 3 inches apart.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'May–Jun', harvest: 'Aug–Oct' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'Apr–Jun', harvest: 'Jul–Sep' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Feb–Apr', harvest: 'May–Jul' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Jan–Mar', harvest: 'Mar–Jun' } } },
  { id: 'lettuce',     name: 'Lettuce',     icon: 'lettuce.png',      plants_per_square: 4,  companions: ['carrot','radish','strawberry','onion','spinach','chamomile'], competitors: [], incompatible: [], notes: 'Bolt-prone in heat. Shade from taller plants in summer.', timing: { cold: { indoor_start: 'Mar–Apr', transplant: 'May–Jun', direct_sow: 'May', harvest: 'Jun–Sep' }, temperate: { indoor_start: 'Feb–Mar', transplant: 'Apr–May', direct_sow: 'Apr–May', harvest: 'May–Jul' }, warm: { indoor_start: 'Jan–Feb', transplant: 'Mar–Apr', direct_sow: 'Mar–Apr', harvest: 'Apr–Jun' }, hot: { indoor_start: 'Oct–Nov', transplant: 'Nov–Dec', direct_sow: 'Oct–Nov', harvest: 'Dec–Mar' } } },
  { id: 'radish',      name: 'Radish',      icon: 'radish.png',       plants_per_square: 16, companions: ['carrot','lettuce','spinach','cucumber','pea'], competitors: [], incompatible: [], notes: 'Fast grower — great for filling gaps and marking slow-germinating rows.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'May–Jun', harvest: 'Jun–Jul' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'Mar–May', harvest: 'Apr–Jun' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Feb–Apr', harvest: 'Mar–May' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Jan–Mar', harvest: 'Feb–Apr' } } },
  { id: 'spinach',     name: 'Spinach',     icon: 'spinach.png',      plants_per_square: 9,  companions: ['lettuce','radish','strawberry','pea'], competitors: [], incompatible: [], notes: 'Cool-season crop. Bolts quickly in heat; plant in spring or fall.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'May–Jun', harvest: 'Jun–Aug' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'Mar–May', harvest: 'Apr–Jun' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Feb–Mar', harvest: 'Mar–May' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Oct–Jan', harvest: 'Nov–Mar' } } },
  { id: 'cucumber',    name: 'Cucumber',    icon: 'cucumber.png',     plants_per_square: 1,  companions: ['radish','nasturtium','sunflower','dill'], competitors: [], incompatible: ['potato'], notes: 'Climbs if given a trellis. Keeps fruit clean and saves space.', timing: { cold: { indoor_start: 'Apr–May', transplant: 'Jun', direct_sow: null, harvest: 'Aug–Sep' }, temperate: { indoor_start: 'Mar–Apr', transplant: 'May–Jun', direct_sow: 'May–Jun', harvest: 'Jul–Sep' }, warm: { indoor_start: 'Feb–Mar', transplant: 'Apr', direct_sow: 'Apr–May', harvest: 'Jun–Aug' }, hot: { indoor_start: null, transplant: 'Mar', direct_sow: 'Mar–Apr', harvest: 'May–Jul' } } },
  { id: 'zucchini',    name: 'Zucchini',    icon: 'zucchini.png',     plants_per_square: 1,  companions: ['nasturtium','corn','pea'], competitors: [], incompatible: [], notes: 'One plant produces prolifically — plan space accordingly.', timing: { cold: { indoor_start: 'Apr–May', transplant: 'Jun', direct_sow: null, harvest: 'Aug–Sep' }, temperate: { indoor_start: 'Mar–Apr', transplant: 'May', direct_sow: 'May', harvest: 'Jul–Sep' }, warm: { indoor_start: 'Feb–Mar', transplant: 'Apr', direct_sow: 'Apr', harvest: 'Jun–Aug' }, hot: { indoor_start: null, transplant: 'Mar', direct_sow: 'Mar–Apr', harvest: 'May–Jul' } } },
  { id: 'pea',         name: 'Pea',         icon: 'peas.png',         plants_per_square: 8,  companions: ['carrot','radish','spinach','lettuce','zucchini','corn'], competitors: [], incompatible: ['onion','garlic'], notes: 'Fixes nitrogen. Supports needed for climbing varieties.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'May', harvest: 'Jul–Aug' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'Mar–Apr', harvest: 'Jun–Jul' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Feb–Mar', harvest: 'Apr–Jun' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Oct–Jan', harvest: 'Dec–Mar' } } },
  { id: 'bush_bean',   name: 'Bush Bean',   icon: 'beans.png',        plants_per_square: 9,  companions: ['carrot','cucumber','strawberry','corn'], competitors: ['onion','fennel'], incompatible: [], notes: 'Do not soak seeds before planting. Direct sow after last frost.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'Jun', harvest: 'Aug–Sep' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'May–Jun', harvest: 'Jul–Aug' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Apr–May', harvest: 'Jun–Jul' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Mar–Apr', harvest: 'May–Jun' } } },
  { id: 'onion',       name: 'Onion',       icon: 'onion.png',        plants_per_square: 16, companions: ['carrot','lettuce','tomato','chamomile'], competitors: ['bush_bean'], incompatible: ['pea'], notes: 'Plant sets or transplants in early spring. Deters many pests.', timing: { cold: { indoor_start: 'Jan–Feb', transplant: 'May', direct_sow: null, harvest: 'Aug–Sep' }, temperate: { indoor_start: 'Jan–Feb', transplant: 'Mar–Apr', direct_sow: 'Mar–Apr', harvest: 'Jul–Aug' }, warm: { indoor_start: 'Nov–Dec', transplant: 'Feb–Mar', direct_sow: 'Feb–Mar', harvest: 'May–Jul' }, hot: { indoor_start: 'Oct–Nov', transplant: 'Dec–Jan', direct_sow: 'Dec–Jan', harvest: 'Mar–May' } } },
  { id: 'garlic',      name: 'Garlic',      icon: 'garlic.png',       plants_per_square: 9,  companions: ['tomato','carrot','strawberry','lettuce'], competitors: [], incompatible: ['pea'], notes: 'Plant cloves in fall for best results. Harvest when lower leaves yellow.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'Sep–Oct', harvest: 'Jul–Aug' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'Oct–Nov', harvest: 'Jun–Jul' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Oct–Dec', harvest: 'May–Jun' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Nov–Jan', harvest: 'Apr–May' } } },
  { id: 'pepper',      name: 'Pepper',      icon: 'chili_pepper.png', plants_per_square: 1,  companions: ['basil','carrot','tomato','marigold'], competitors: [], incompatible: ['fennel'], notes: 'Needs warm soil. Start indoors 8–10 weeks before last frost.', timing: { cold: { indoor_start: 'Feb–Mar', transplant: 'Jun', direct_sow: null, harvest: 'Aug–Oct' }, temperate: { indoor_start: 'Feb–Mar', transplant: 'May–Jun', direct_sow: null, harvest: 'Jul–Sep' }, warm: { indoor_start: 'Jan–Feb', transplant: 'Apr', direct_sow: null, harvest: 'Jun–Sep' }, hot: { indoor_start: 'Nov–Dec', transplant: 'Feb–Mar', direct_sow: null, harvest: 'Apr–Jul' } } },
  { id: 'broccoli',    name: 'Broccoli',    icon: 'broccoli.png',     plants_per_square: 1,  companions: ['chamomile','dill','nasturtium','onion'], competitors: ['tomato','strawberry'], incompatible: [], notes: 'Cool-season brassica. Side-dress with nitrogen fertiliser.', timing: { cold: { indoor_start: 'Mar–Apr', transplant: 'May–Jun', direct_sow: null, harvest: 'Aug–Oct' }, temperate: { indoor_start: 'Feb–Mar', transplant: 'Apr–May', direct_sow: null, harvest: 'Jun–Aug' }, warm: { indoor_start: 'Aug–Sep', transplant: 'Oct', direct_sow: null, harvest: 'Dec–Feb' }, hot: { indoor_start: 'Aug–Sep', transplant: 'Oct–Nov', direct_sow: null, harvest: 'Jan–Mar' } } },
  { id: 'cauliflower', name: 'Cauliflower', icon: 'cauliflower.png',  plants_per_square: 1,  companions: ['dill','onion','chamomile'], competitors: ['tomato','strawberry'], incompatible: [], notes: 'Blanch heads by tying leaves over the curd when it is golf-ball size.', timing: { cold: { indoor_start: 'Mar–Apr', transplant: 'May–Jun', direct_sow: null, harvest: 'Aug–Oct' }, temperate: { indoor_start: 'Feb–Mar', transplant: 'Apr–May', direct_sow: null, harvest: 'Jun–Aug' }, warm: { indoor_start: 'Aug–Sep', transplant: 'Oct', direct_sow: null, harvest: 'Dec–Feb' }, hot: { indoor_start: 'Aug–Sep', transplant: 'Oct–Nov', direct_sow: null, harvest: 'Jan–Mar' } } },
  { id: 'kale',        name: 'Kale',        icon: 'kale.png',         plants_per_square: 1,  companions: ['dill','chamomile','nasturtium'], competitors: ['tomato'], incompatible: [], notes: 'Very cold-hardy. Flavour improves after frost.', timing: { cold: { indoor_start: 'Mar–Apr', transplant: 'May', direct_sow: 'Jul–Aug', harvest: 'Aug–Nov' }, temperate: { indoor_start: 'Feb–Mar', transplant: 'Apr', direct_sow: 'Jul', harvest: 'Jun–Nov' }, warm: { indoor_start: 'Aug–Sep', transplant: 'Sep–Oct', direct_sow: 'Sep–Oct', harvest: 'Nov–Mar' }, hot: { indoor_start: 'Sep–Oct', transplant: 'Oct–Nov', direct_sow: 'Oct–Nov', harvest: 'Dec–Apr' } } },
  { id: 'strawberry',  name: 'Strawberry',  icon: 'strawberry.png',   plants_per_square: 4,  companions: ['lettuce','spinach','garlic','bush_bean'], competitors: ['broccoli','cauliflower'], incompatible: ['fennel'], notes: 'Perennial. Runners spread aggressively — remove or redirect.', timing: { cold: { indoor_start: null, transplant: 'May', direct_sow: null, harvest: 'Jun–Jul' }, temperate: { indoor_start: null, transplant: 'Apr', direct_sow: null, harvest: 'May–Jul' }, warm: { indoor_start: null, transplant: 'Mar', direct_sow: null, harvest: 'Apr–Jun' }, hot: { indoor_start: null, transplant: 'Oct–Nov', direct_sow: null, harvest: 'Feb–Apr' } } },
  { id: 'potato',      name: 'Potato',      icon: 'potato.png',       plants_per_square: 1,  companions: ['corn','pea','nasturtium','chamomile'], competitors: ['tomato'], incompatible: ['cucumber'], notes: 'Plant certified seed potatoes. Hill soil up as plants grow.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'May–Jun', harvest: 'Sep–Oct' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'Mar–Apr', harvest: 'Jul–Aug' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Feb–Mar', harvest: 'Jun–Jul' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Jan–Feb', harvest: 'Apr–May' } } },
  { id: 'corn',        name: 'Corn',        icon: 'corn.png',         plants_per_square: 1,  companions: ['potato','pea','zucchini','cucumber','sunflower'], competitors: ['tomato'], incompatible: [], notes: 'Wind-pollinated — plant in blocks, not rows, for best pollination.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'Jun', harvest: 'Sep–Oct' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'May–Jun', harvest: 'Aug–Sep' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Apr–May', harvest: 'Jul–Aug' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Mar–Apr', harvest: 'Jun–Jul' } } },
  { id: 'sunflower',   name: 'Sunflower',   icon: 'sunflower.png',    plants_per_square: 1,  companions: ['cucumber','corn','nasturtium'], competitors: [], incompatible: ['potato'], notes: 'Attracts pollinators. Provides shade for heat-sensitive plants.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'Jun', harvest: 'Sep–Oct' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'May', harvest: 'Aug–Sep' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Apr', harvest: 'Jul–Aug' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Mar–Apr', harvest: 'Jun–Aug' } } },
  { id: 'fennel',      name: 'Fennel',      icon: 'fennel.png',       plants_per_square: 1,  companions: ['dill'], competitors: ['bush_bean'], incompatible: ['tomato','pepper','basil','strawberry'], notes: 'Allelopathic — inhibits most vegetables. Best grown in its own container or bed edge.', timing: { cold: { indoor_start: 'Apr', transplant: 'Jun', direct_sow: null, harvest: 'Sep–Oct' }, temperate: { indoor_start: 'Mar', transplant: 'May', direct_sow: 'Apr–May', harvest: 'Aug–Sep' }, warm: { indoor_start: 'Feb', transplant: 'Apr', direct_sow: 'Mar–Apr', harvest: 'Jul–Aug' }, hot: { indoor_start: null, transplant: 'Mar', direct_sow: 'Feb–Mar', harvest: 'May–Jul' } } },
  { id: 'dill',        name: 'Dill',        icon: 'dill.png',         plants_per_square: 4,  companions: ['cucumber','fennel','broccoli','cauliflower','kale'], competitors: [], incompatible: ['carrot'], notes: 'Attracts beneficial wasps. Allow some plants to flower.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'Jun', harvest: 'Jul–Sep' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'Apr–Jun', harvest: 'Jun–Aug' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Mar–May', harvest: 'May–Jul' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Feb–Mar', harvest: 'Apr–Jun' } } },
  { id: 'marigold',    name: 'Marigold',    icon: 'marigold.png',     plants_per_square: 4,  companions: ['tomato','basil','pepper','carrot','cucumber'], competitors: [], incompatible: [], notes: 'Natural pest deterrent. Deters nematodes and aphids.', timing: { cold: { indoor_start: 'Mar–Apr', transplant: 'Jun', direct_sow: null, harvest: null }, temperate: { indoor_start: 'Feb–Mar', transplant: 'May', direct_sow: 'May', harvest: null }, warm: { indoor_start: 'Jan–Feb', transplant: 'Apr', direct_sow: 'Apr', harvest: null }, hot: { indoor_start: null, transplant: 'Mar', direct_sow: 'Mar', harvest: null } } },
  { id: 'nasturtium',  name: 'Nasturtium',  icon: 'nasturtium.png',   plants_per_square: 4,  companions: ['tomato','cucumber','zucchini','potato','broccoli','sunflower'], competitors: [], incompatible: [], notes: 'Edible flowers and leaves. Sacrificial trap crop for aphids.', timing: { cold: { indoor_start: null, transplant: null, direct_sow: 'Jun', harvest: 'Jul–Sep' }, temperate: { indoor_start: null, transplant: null, direct_sow: 'Apr–May', harvest: 'Jun–Sep' }, warm: { indoor_start: null, transplant: null, direct_sow: 'Mar–Apr', harvest: 'May–Aug' }, hot: { indoor_start: null, transplant: null, direct_sow: 'Feb–Mar', harvest: 'Apr–Jun' } } },
  { id: 'chamomile',   name: 'Chamomile',   icon: 'chamomile.png',    plants_per_square: 4,  companions: ['tomato','carrot','lettuce','onion','broccoli','cauliflower','kale','potato'], competitors: [], incompatible: [], notes: 'Accumulates calcium and potassium. Attracts beneficial insects.', timing: { cold: { indoor_start: 'Mar–Apr', transplant: 'May–Jun', direct_sow: 'May', harvest: 'Jul–Sep' }, temperate: { indoor_start: 'Feb–Mar', transplant: 'Apr–May', direct_sow: 'Apr', harvest: 'Jun–Aug' }, warm: { indoor_start: 'Jan–Feb', transplant: 'Mar–Apr', direct_sow: 'Mar', harvest: 'May–Jul' }, hot: { indoor_start: null, transplant: 'Feb–Mar', direct_sow: 'Feb', harvest: 'Apr–Jun' } } },
]

async function seed() {
  console.log(`Seeding ${plants.length} plants…`)

  const { error } = await supabase
    .from('plants')
    .upsert(plants, { onConflict: 'id' })

  if (error) {
    console.error('Seed failed:', error.message)
    process.exit(1)
  }

  console.log(`Done — ${plants.length} plants upserted.`)
}

seed()
